### ISSUE TITLE
Clarifying usage with associations

### ISSUE THREAD

**Issue by oyeanuj** [wbotelhos/idy#2]
Hi @wbotelhos, thank you for creating this library! In my setup, I have a Rails API server with a separate client and often have request of the following nature
```rb
# Create Book
book: {
  author_id: 382nfkjs,
  name: "The Dummy's guide to Obfuscating Ids"
}
```

Assuming in this case that both `Book` and `Author` model are using `idy`, can I pass in the idy-ed `author_id` or do I have to first convert it back to a non-obfuscated id?

Another version of the same problem is when serializing the book object, by default, any serializer would insert the database `author_id`. Is there a way to ensure that the `obfuscated` id is inserted? Or do I have to do something like this?
```rb
# Book
def get_author_id
  self.author.to_param.id
end
```

Thank you!

**Comment by wbotelhos** [comment]
Hi @oyeanuj ,

You can't set the `idy` value as an `id` value. It is just a representation that is translated by the overrided `to_param` method.

Said that, the best thing to do is always load the object before you insert the child object like this:

```ruby
def create
  book             = Book.new(params.require('book').permit(:name))
  book.author = Author.find(params['author_id'])

  book.save
end
```

This way, you makes sure that no wrong object will be inserted and you can give a feedback to the user about that. Cases where you need to find this foreign object scoped by some other relation, like, my library or your library, this case is better, since you have the chance to check it.

**Comment by oyeanuj** [comment]
@wbotelhos Thank you for the response. Just to make sure I am understanding this correctly, essentially - Instead of using an `id` param directly, you are suggesting that I load the object specified in the params. That sounds doable if maybe a little non-performant if there is more than one id.

What are your thoughts on having a function like similar to `findy` but for `save`, `update` which if given the id, would just replace the idy(s) with `id`?

Also, can one assume that a given object will always have map to the same `id` consistently?

**Comment by wbotelhos** [comment]
Override the `save`, and `update` is dangerous and painful to keep compatibility and track all cousins methods like `find_or_create_by` etc...

The gem makes the job of presentation, but not of persistence. I understand that it will be a load more and it will be slower than to pass the idy directly and inside it has a translation to the original id.

Maybe we can expose the decode method to be possible something like:

```ruby
def create
  book = Book.new(params.require('book').permit(:name))
  book.author = Author.idy_from(params['author_id']) # or from_idy...

  book.save
end
```

But event that will need a interceptor, since makes a monkey patch on AR is not a nice thing. What do you think?

**Comment by wbotelhos** [comment]
@oyeanuj By the way, we already have this method, but is not documented:

```
Author.idy_decode '382nfkjs'
```

This will do the trick, but you will need to iterate on your hash to decode the idy value.

**Comment by oyeanuj** [comment]
@wbotelhos Thanks for engaging! I think the `decode` or the proposed `from_idy` method would work well for the time being since the `save_via_idy` method that I was thinking about would have just decoded the `idy` to the correct `id` and then call the save method (no overriding or monkeypatching).

Also, can one assume that a given object will always have map to the same id consistently?

**Comment by wbotelhos** [comment]
I think you can, but the Model will always have a different name. The Salt will be different and if some day it fails, you can provide your own `salt` like `Time.current` equivalent as `created_at` of the object and it will be unique anyway.

**Comment by oyeanuj** [comment]
Got it, so the safest way would be practice would be something like this?
```rb
class Article < ApplicationRecord
  idy salt: Time.at(self.created_at).to_i
end
```

Or is it that as long as salt doesn't change, the `idy` would not change either?

**Comment by wbotelhos** [comment]
If the salt changes, your ID will be changed to. So you can keep a column read-only with a fixed salt and concat it with the name and id of the self class. You can mix a bouch of things.

You can read it here: http://hashids.org/ruby

**Comment by wbotelhos** [comment]
@oyeanuj I'm closing that since you can use the method `Model.idy_decode(idy)` [documented here](https://github.com/wbotelhos/idy#functions).
